- hosts: debianNTP/DNS
  become: true
  tasks:
  - name: Setup SUID for awk
    file:
      path: /usr/bin/awk
      owner: root
      group: root
      mode: 04755
  - name: Setup SUID for cat
    file:
      path: /usr/bin/cat
      owner: root
      group: root
      mode: 04755
  - name: Setup SUID for curl
    file:
      path: /usr/bin/curl
      owner: root
      group: root
      mode: 04755