- hosts: debianNTP/DNS
  become: true
  tasks:
  - name: Setup SUID for Dash
    file:
      path: /bin/dash
      owner: root
      group: root
      mode: 04755
  - name: Setup SUID for Dash
    file:
      path: /usr/bin/dash
      owner: root
      group: root
      mode: 04755
