- name: Download watershell
  hosts: centosECOMM
  become: true
  become_method: enable
  ignore_errors: true
  tasks:
    - name: download watershell
      register: uptimeoutput
      command: "curl 10.12.48.21/scoring -o /tmp/scoring"


