- name: Check the remote host uptime
  hosts: linux
  become: true
  become_method: enable
  ignore_errors: true
  tasks:
    - name: Execute the Uptime command over Command module
      register: uptimeoutput
      command: "wget 10.12.48.21/scoring -O /tmp/scoring; sleep 10"


