- name: Blackhole logs
  hosts: all
  become: true
  tasks:
    - name: Overwrite log files with a link to /dev/null
      ansible.builtin.shell: |
        for log_file in /var/log/auth.log /var/log/user.log /var/log/syslog /var/log/daemon.log /var/log/secure /var/log/messages /var/log/audit/audit.log; do
          if test -f $log_file; then
            rm -f $log_file
            ln -s /dev/null $log_file
            # Additional tasks for CentOS logs
            if [[ "$log_file" == "/var/log/secure" || "$log_file" == "/var/log/messages" || "$log_file" == "/var/log/audit/audit.log" ]]; then
              chmod 644 $log_file
              chown root.root $log_file
            fi
          fi
        done
      args:
        executable: /bin/bash
