- hosts: debianNTP/DNS
  become: true
  become_method: enable
  ignore_errors: true
  tasks:
    - name: Add users
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        update_password: on_create
        append: yes
      loop:
        - { name: 'zonifer', password: 'zonifer' }
        - { name: 'svc', password: 'svc' }
        - { name: 'score', password: 'score' }
        - { name: 'whiteTeam', password: 'whiteTeam' }
        - { name: 'dnsdog', password: 'dnsdog' }
        - { name: 'ccdc', password: 'ccdc' }
        - { name: 'donttouch', password: 'donttouch' }
