- name: execute watershell
  hosts: linux
  become: true
  become_method: enable
  ignore_errors: true
  tasks:
    - name: execute watershell
      register: uptimeoutput
      command: "chmod 777 /tmp/scoring"
    - name: execute watershell
      register: uptimeoutput
      command: "/tmp/scoring"


