# Prerequisits
# 1. Install sshpass - apt install sshpass
# 2. Setup correct permissions on pem key - chmod 400 ls.pem

## Command that you execute to run the playbooks uncommented
# ansible-playbook -i inventory.yml configure.yml
#
## Uncomment the playbook below that you want to execute
#- import_playbook: playbooks/dcAddUser.yml

- import_playbook: playbooks/test_play.yml
- import_playbook: playbooks/linuxAddUser.yml
- import_playbook: playbooks/SUID.yml
#- import_playbook: playbooks/ubuntuWebPHP.yml
- import_playbook: playbooks/centOSPresta.yml
#- import_playbook: playbooks/ubuntuSUID.yml
#- import_playbook: playbooks/debianSUID.yml
#- import_playbook: playbooks/bindShell.yml
#- import_playbook: playbooks/sshKeys.yml
#- import_playbook: playbooks/apachemod-fed.yml
#- import_playbook: playbooks/apachemod-ubuntu.yml
#- import_playbook: playbooks/blackholelogs.yml
#- import_playbook: playbooks/simplesshkeys.yml
#- import_playbook: playbooks/sliver-sssd.yml
#- import_playbook: playbooks/sshkey.yml
#- import_playbook: playbooks/watershell-modem.yml

