all:
  children:
    linux:
      hosts:
        centosECOMM:
          ansible_host: "172.25.28.11"
          ansible_port: "22"
          ansible_connection: "ssh"
          ansible_ssh_common_args: "-o HostKeyAlgorithms=+ssh-dss"
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
          ansible_user: "{{ centosECOMMUser }}"
          ansible_password: "{{ centosECOMMPass }}"
        fedoraMailWeb:
          ansible_host: "172.25.28.39"
          ansible_port: "22"
          ansible_connection: "ssh"
          ansible_ssh_common_args: "-o HostKeyAlgorithms=+ssh-dss"
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
          ansible_user: "{{ fedoraUser }}"
          ansible_password: "{{ fedoraPass }}"
          ansible_python_interpreter: "/usr/bin/python"
        debianNTP/DNS:
          ansible_host: "172.25.28.20"
          ansible_port: "22"
          ansible_connection: "ssh"
          ansible_ssh_common_args: "-o HostKeyAlgorithms=+ssh-dss"
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
          ansible_user: "{{ debianUser }}"
          ansible_password: "{{ debianPass }}"
          become: true
          ansible_become_user: "root"
          ansible_become_pass: "changeme"
          ansible_become_method: su
        ubuntuWeb:
          ansible_host: "172.25.28.23"
          ansible_port: "22"
          ansible_connection: "ssh"
          ansible_ssh_common_args: "-o HostKeyAlgorithms=+ssh-dss"
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
          ansible_user: "{{ ubuntuWebUser }}"
          ansible_password: "{{ ubuntuWebPass }}"
          ansible_python_interpreter: "/usr/bin/python2"
          ansible_become_pass: "changeme"

  vars:
    centosECOMMUser: "root"
    centosECOMMPass: "changeme"
    fedoraUser: "root"
    fedoraPass: "!Password123"
    splunkUser: "root"
    splunkPass: "changemenow"
    debianUser: "sysadmin"
    debianPass: "changeme"
    ubuntuWebUser: "sysadmin"
    ubuntuWebPass: "changeme"
